from pathlib import Path


ENVIRONMENT_ID = "LunarLander-v3"

DEFAULT_EPISODES = 100
DEFAULT_SEED = 42
DEFAULT_MAX_STEPS = 1000

DEFAULT_REPORT_PATH = Path(
    "reports/random_agent_baseline.json"
)

DEFAULT_MINIMUM_MEAN_REWARD = -300.0
DEFAULT_MAXIMUM_TRUNCATED_EPISODES = 10
DEFAULT_MINIMUM_SUCCESSFUL_EPISODES = 0

DEFAULT_DQN_TIMESTEPS = 1_000
DEFAULT_DQN_MODEL_PATH = Path("models/dqn_lunar_lander.zip")

DEFAULT_DQN_EVALUATION_EPISODES = 20
DEFAULT_DQN_REPORT_PATH = Path("reports/dqn_evaluation.json")

DQN_LEARNING_RATE = 6.3e-4
DQN_BATCH_SIZE = 128
DQN_BUFFER_SIZE = 50_000
DQN_LEARNING_STARTS = 0
DQN_GAMMA = 0.99
DQN_TARGET_UPDATE_INTERVAL = 250
DQN_TRAIN_FREQ = 4
DQN_GRADIENT_STEPS = -1
DQN_EXPLORATION_FRACTION = 0.12
DQN_EXPLORATION_FINAL_EPS = 0.1
DQN_NETWORK_ARCHITECTURE = [256, 256]

DEFAULT_DQN_EVAL_FREQ = 10_000
DEFAULT_DQN_EVAL_EPISODES_DURING_TRAINING = 10
DEFAULT_DQN_CHECKPOINT_FREQ = 25_000