from pathlib import Path


ENVIRONMENT_ID = "LunarLander-v3"

DEFAULT_EPISODES = 100
DEFAULT_SEED = 42
DEFAULT_MAX_STEPS = 1000

DEFAULT_REPORT_PATH = Path(
    "reports/random_agent_baseline.json"
)

DEFAULT_MINIMUM_MEAN_REWARD = -300.0
DEFAULT_MAXIMUM_TRUNCATED_EPISODES = 10
DEFAULT_MINIMUM_SUCCESSFUL_EPISODES = 0